/* 
 * $Id: cwritepwf.c,v 1.4 2004/06/16 20:46:17 mbarnes Exp $
 */

/****************************************************************************
 *                                                                          *
 * Mimic the output generated by writepwf.f                                 *
 *                                                                          *
 ****************************************************************************/

#include <ctype.h>
#include <stdio.h>

void cwritepwf_(FILE *fp, char *symbol, double *zeff, int *npspt0, int *nflq,
                int *iproj, int *idi, char *xproj, char *xrpcc, int *igrid,
                double *spacing, double *first, int *numa, double *aorad, char *xao){

  /* annoying thing in bh that the symbol cant start with a space, so 
     interchange the characters */

  if (isspace(symbol[0])) {
    symbol[0] = symbol[1];
    symbol[1] = ' ';
  }

  fprintf(fp, "# Opium generated file\n");
  fprintf(fp, "%-2s                      : Element Symbol\n", symbol);
  fprintf(fp, "%4.1f                    : Zeff\n", *zeff);
  fprintf(fp, "%4d                    : # Local grid points\n", *npspt0);
  fprintf(fp, "y                       : dV/dr?\n");
  fprintf(fp, "%4d %1d                  : # non-local grid points, #proj\n",
          *nflq, *iproj);
  fprintf(fp, "y                       : dV/dr?\n");
  fprintf(fp, "%4s                    : projs\n", xproj);
  fprintf(fp, "y                       : AOs in file?\n");
/*  fprintf(fp, "n                       : AOs in file?\n"); */
  fprintf(fp, "%1s                       : PCC in file?\n", xrpcc);
  fprintf(fp, "%4d%7.4f%7.4f %1d    : # AO grid points,h,r1,#AOs in file\n",
          *igrid, *spacing, *first, *idi);
  fprintf(fp, "%2d%4.1f                  : # AOs per atom,AO radius\n",
          *numa, *aorad);
/*  fprintf(fp, "none                    : AO ordering\n"); */

  fprintf(fp, "%-7s                : AO ordering\n", xao);
  
}
                
                
