/*
 * Copyright (c) 1998-2012 The OPIUM Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */
/* 
 */

/****************************************************************************
 *                                                                          *
 * Mimic the output generated by writepwf.f                                 *
 *                                                                          *
 ****************************************************************************/

#include <ctype.h>
#include <stdio.h>

void cwritepwf_(FILE *fp, char *symbol, double *zeff, int *npspt0, int *nflq,
                int *iproj, int *idi, char *xproj, char *xrpcc, int *igrid,
                double *spacing, double *first, int *numa, double *aorad){

  /* annoying thing in bh that the symbol cant start with a space, so 
     interchange the characters */

  if (isspace(symbol[0])) {
    symbol[0] = symbol[1];
    symbol[1] = ' ';
  }
  
  fprintf(fp, "# Opium generated file\n");
  fprintf(fp, "%-2s                      : Element Symbol\n", symbol);
  fprintf(fp, "%4.1f                    : Zeff\n", *zeff);
  fprintf(fp, "%4d                    : # Local grid points\n", *npspt0);
  fprintf(fp, "y                       : dV/dr?\n");
  fprintf(fp, "%4d %1d                  : # non-local grid points, #proj\n",
          *nflq, *iproj);
  fprintf(fp, "y                       : dV/dr?\n");
  fprintf(fp, "%4s                       : projs\n", xproj);
  fprintf(fp, "y                       : AOs in file?\n");
  fprintf(fp, "%1s                       : PCC in file?\n", xrpcc);
  fprintf(fp, "%4d%7.4f%7.4f %1d    : # AO grid points,h,r1,#AOs in file\n",
          *igrid, *spacing, *first, *idi);
  fprintf(fp, "%4.1f                  : AO radius\n",
          *aorad);
}
                
                
