#include "cdim.h"
      parameter(npdm = NPDM)
      parameter(n0 = N0) 
      parameter(npl0 = NPL0)
      parameter(nvale0=NVALE0)

      parameter(nout=7)
      parameter(numfn0 = 50)
      parameter(nquad0 = 50)
      parameter(tol2 = 1.0e-9)
      parameter(nfam0 = 10)
      parameter(nintm0 = 2**(nfam0-1))
      parameter(maxflq = 2001)
      parameter(npspt0 = 4002)
      parameter(nrmax = 10000)
      parameter(lmax = 4)
      parameter(norbp = 100)
